# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=40)),
                ('role', models.CharField(blank=True, default='', max_length=20)),
                ('photo_url', models.CharField(blank=True, default='', max_length=20)),
                ('self_intro', models.TextField()),
                ('area1', models.TextField()),
                ('area2', models.TextField()),
                ('area3', models.TextField()),
                ('expectations', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
